apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-bgdg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-bgdg
    app.kubernetes.io/part-of: jvm-build-suite-application-cvqa
  name: jvm-build-suite-component-bgdg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-bgdg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-bgdg
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/jvm-build-emgn-tenant/jvm-build-suite-application-cvqa/jvm-build-suite-component-bgdg@sha256:0f665db8bcc07c6056336e0c391f32c251c452c817f8d803494e47e9bab66373
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
